### ISSUE TITLE
Question: Where is a document for BUNDLE_APP_CONFIG?

### ISSUE THREAD

**Issue by ybiquitous** [rubygems/bundler#7085]
Hi,

I find the code about `BUNDLE_APP_CONFIG`, but I can't find a document for it. 😢 

https://github.com/bundler/bundler/blob/61a56579cb6232fc02967ea2264b623ee64f16c6/lib/bundler.rb#L242-L248

![image](https://user-images.githubusercontent.com/473530/55317317-38c3af00-54ab-11e9-9971-9db8ac6813e7.png)
-- https://bundler.io/v2.0/bundle_config.html

Does it exist somewhere actually? Or are there any reasons for which it isn't written?

I would be happy if I could get some answers. Thanks.

**Comment by deivid-rodriguez** [comment]
I don't think this is currently undocumented. PR welcomed!
