### ISSUE TITLE
SSLError does not report the actual problem

### ISSUE THREAD

**Issue by p-mongo** [rubygems/bundler#7192]
I obtained the following output from bundler in our CI environment:

<pre>
[2019/06/07 12:49:12.626] + bundle install
[2019/06/07 12:49:12.626] [mongo] Warning: No private key present, creating unsigned gem.
[2019/06/07 12:49:12.647] Could not load OpenSSL.
[2019/06/07 12:49:12.647] You must recompile Ruby with OpenSSL support or change the sources in your
[2019/06/07 12:49:12.647] Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using
[2019/06/07 12:49:12.647] RVM are available at http://rvm.io/packages/openssl.
[2019/06/07 12:49:12.648] Command failed: command encountered problem: exit status 1
</pre>

As far as I can tell, the Ruby installation I am using does have openssl extension compiled and loadable. Therefore I am stumped as to what the cause of this bundler failure is.

Looking at the code in fetcher.rb, when this exception is raised, bundler does not actually attempt to load openssl. It is not immediately obvious to me how to make bundler report the actual error.

**Comment by p-mongo** [comment]
After going through bundler source again it seems that `--verbose` option would produce the full exception report, however I instead get this:

<pre>
[2019/06/07 16:25:31.202] Bundler version 2.0.1
Running `bundle install --verbose` with bundler 2.0.1
</pre>

... and then the same output as above without the actual exception information.

It seems to me that either `--verbose` is not forwarded correctly when bundler invokes itself, despite the log output claiming it is forwarded, or this option does not output the SSLError exception information.

**Comment by duckinator** [comment]
If you're still having this problem, can you provide more information about your CI environment?  E.g. operating system+version, Ruby version, etc?

**Comment by p-mongo** [comment]
The problem I am reporting in this issue concerns this exception: https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher.rb#L35

This exception should contain the reason why openssl could not be loaded. For example, it should include the ImportError instance/message/backtrace when such load was attempted.

The issue is not environment-specific.

**Comment by p-mongo** [comment]
To reproduce this, remove `openssl.so` and try to `bundle install` any project (e.g. https://github.com/mongodb/bson-ruby):

<pre>
speed% find ~/.rbenv/versions/2.6/|grep ssl|grep so
/home/sandbox/.rbenv/versions/2.6/lib/ruby/2.6.0/x86_64-linux/openssl.so
/home/sandbox/.rbenv/versions/2.6/share/ri/2.6.0/system/Net/SMTP/ssl_socket-i.ri
speed% rm /home/sandbox/.rbenv/versions/2.6/lib/ruby/2.6.0/x86_64-linux/openssl.so
speed% bundle install                                                             
[bson] Warning: No private key present, creating unsigned gem.

Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL
using RVM are available at http://rvm.io/packages/openssl.
</pre>

**Comment by p-mongo** [comment]
Turns out the problem was bundler's handling of LoadError, I seem to have missed that the message referenced in this ticket existed in two copies.

**Comment by p-mongo** [comment]
In our case the actual error is as follows:

<pre>
Could not load OpenSSL: LoadError: /lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by .../src/rubies/ruby-2.6.5/lib/ruby/2.6.0/powerpc-linux-gnu/openssl.so) - .../src/rubies/ruby-2.6.5/lib/ruby/2.6.0/powerpc-linux-gnu/openssl.so
</pre>

When this error is reported, it is immediately apparent what the problem is. Without this error message (i.e. current bundler behavior as described in this issue), the problem is impossible to diagnose.
