### ISSUE TITLE
capistrano: can't modify frozen object using a github repo

### ISSUE THREAD

**Issue by omsoft** [rubygems/bundler#7377]
If I use **gem "pdfkit", "0.4.6"** from rubygems everything works fine.
But when I switch to a github repo like this:

`gem "pdfkit", :git => "https://github.com/omsoft/pdfkit.git", :tag => "v0.4.6"`

I get these errors:

```
 **Retrying source fetch due to error (2/3): TypeError can't modify frozen object
 ** Retrying source fetch due to error (3/3): TypeError can't modify frozen object
 ** Unfortunately, a fatal error has occurred. Please see the Bundler
 ** troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
***  /containers/30028/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/net/https.rb:138:in `verify_mode='
*** : can't modify frozen object (TypeError)
***  from /containers/30028/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/net/https.rb:138:in `verify_mode='
```

I'm using bundler 1.6.5. The command used by capistrano is:

`bundle install --gemfile /containers/30028/myapplication_name/releases/20191010104232/Gemfile --path /containers/30028/myapplication_name/shared/bundle --deployment --quiet --without development test`

Why this is happening?

**Comment by deivid-rodriguez** [comment]
It sounds like you're using ruby 1.8.7 and bundler 1.6.5. Those are really ancient, can you upgrade to a newer ruby & bundler version and try again?

**Comment by colby-swandale** [comment]
No reply from original author. Closing.
