### ISSUE TITLE
Missing bundle-viz repo

### ISSUE THREAD

**Issue by JunichiIto** [rubygems/bundler#7560]
In https://github.com/bundler/bundler/blob/master/UPGRADING.md ,  bundle-viz repo is located  https://github.com/bundler/bundle-viz , but I cannot find it. (Maybe is it a private repo?)

**Comment by hsbt** [comment]
I couldn't find the `bundle-viz` in https://github.com/bundler/bundler/blob/master/UPGRADING.md. Can you point the its detail?

**Comment by JunichiIto** [comment]
It's written as a link:

https://raw.githubusercontent.com/bundler/bundler/master/UPGRADING.md

```
* `bundle viz` will be removed and extracted to a plugin.

  This is the only bundler command requiring external dependencies, both an OS
  dependency (the `graphviz` package) and a gem dependency (the `ruby-graphviz`
  gem). Removing these dependencies will make development easier and it was also
  seen by the bundler team as an opportunity to develop a [bundler
  plugin](https://github.com/bundler/bundle-viz) that it's officially maintained
  by the bundler team, and that users can take as a reference to develop their
  own plugins. The plugin contains the same code as the old core command, the
  only difference being that the command is now implemented as `bundle graph`
  hich is much easier to understand. Have a look at the plugin's repo for more
  information about how to install and use the new plugin.
```

**Comment by hsbt** [comment]
Thanks, I think its the future plan section.

**Comment by JunichiIto** [comment]
I'm not sure my opinion is right but the link should be removed since it is not available now. I submit PR for it with some other fixes:

https://github.com/rubygems/bundler/pull/7561

**Comment by deivid-rodriguez** [comment]
Yeah, I agree it's better to remove the invalid link for now until we make a decision on naming and review the plugin. There's currently several options, the most promising seems @fatkodima's plugin because it has been recently updated, but we need to decide on naming, whether to move it to the `rubygems` organization or keep it external, and review the plugin. See https://github.com/rubygems/bundler/issues/7041.

**Comment by JunichiIto** [comment]
Thank you for information. I could understand the current status about the plugin.
