### ISSUE TITLE
Help with the --standalone option

### ISSUE THREAD

**Issue by gerases** [rubygems/bundler#7571]
Hi,

I'm trying to understand why after using the `--standalone` followed by `--deployment`, `bundler/setup.rb` doesn't become part of the application. As a result, I have to install bundler of the right version as a separate step. I must be missing something simple here?

Thanks for any insight!

**Comment by duckinator** [comment]
On my system, `--standalone --deployment` creates `vendor/bundle/bundler/setup.rb` plus a bunch of stuff in `vendor/bundle/ruby`. In order to use the `bundler/setup` it creates, I have to do `ruby -I vendor/bundle /path/to/some/script.rb`. Perhaps you need to do something like that?

**Comment by colby-swandale** [comment]
ping @gerases did you resolve your issue?

**Comment by gerases** [comment]
@colby-swandale, it's been long enough for me to forget about the details of what I eventually did, but the reply came after I did that :) Next time I re-package rspec-puppet, I'll consult this thread. 

Thank you much for bundler all the same!
