### ISSUE TITLE
LoadError: cannot load such file -- bundler/setup

### ISSUE THREAD

**Issue by tetron** [rubygems/bundler#7573]
Ruby 2.3

bundler 2.1.4

Installed using "gem install bundler"

GEM_HOME=/var/lib/gems

When running "bundle exec rake" in a Ruby on Rails 5 project:

```
arvbox@043edfea0b4d:/usr/src/arvados/apps/workbench$ bundle exec rake npm:install
rake aborted!
LoadError: cannot load such file -- bundler/setup
/usr/src/arvados/apps/workbench/config/boot.rb:10:in `require'
/usr/src/arvados/apps/workbench/config/boot.rb:10:in `<top (required)>'
/usr/src/arvados/apps/workbench/config/application.rb:5:in `require'
/usr/src/arvados/apps/workbench/config/application.rb:5:in `<top (required)>'
/usr/src/arvados/apps/workbench/Rakefile:9:in `require'
/usr/src/arvados/apps/workbench/Rakefile:9:in `<top (required)>'
/var/lib/gems/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/var/lib/gems/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/var/lib/gems/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/var/lib/gems/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/var/lib/gems/bin/bundle:22:in `load'
/var/lib/gems/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```

I expect to be able to `require` bundler since it is a dependency of Rails in Gemfile.lock:

```
    rails (5.0.7.2)
      ...
      bundler (>= 1.3.0)
```

`bundle install --verbose` reports the bundler dependency is fulfilled:

```
...
Using bundler 2.1.4
0:  bundler (2.1.4) from /var/lib/gems/gems/bundler-2.1.4/lib/bundler/source
...
```

I used `bundler console` to get the search path from `$:`.  This shows that the search path for `bundler` is wrong (should be `/var/lib/gems/gems/bundler-2.1.4/lib` but an extra `gems/bundler-2.1.4/lib` has been added to the end):

```
[..., "/var/lib/gems/gems/bundler-2.1.4/lib/gems/bundler-2.1.4/lib"]
```

As a workaround, I am able to downgrade to bundler 2.0.2.  In this version, the search path includes both correct and incorrect paths:

```
[..., "/var/lib/gems/gems/bundler-2.0.2/lib", ..., "/var/lib/gems/gems/bundler-2.0.2/lib/gems/bundler-2.1.4/lib"]
```

**Comment by deivid-rodriguez** [comment]
I have seen this issue in the past, but I can no longer reproduce it. Could you post repro steps for me?

**Comment by tetron** [comment]
This happens to me in a Docker container so let me see if I can come up with a minimal Dockerfile that reproduces the error.

**Comment by deivid-rodriguez** [comment]
Thanks! Docker is great for repros :+1:.

**Comment by tetron** [comment]
@deivid-rodriguez I just discovered that I may need to update `gem` alongside `bundler` -- I haven't confirmed that's causing this bug, but perhaps `bundler` could warn if the `gem` version is too old?

**Comment by tetron** [comment]
Yes, after I updated RubyGems it started working again.  A warning from `bundler` about upgrading RubyGems would probably save a lot of people some trouble.

**Comment by deivid-rodriguez** [comment]
I'd still appreciate the repro because bundler is expected to support older rubygems versions too.
