### ISSUE TITLE
Outdated reference to pullreview.com

### ISSUE THREAD

**Issue by duckinator** [rubygems/bundler#7579]
[doc/contributing/HOW_YOU_CAN_HELP.md](https://github.com/rubygems/bundler/blob/master/doc/contributing/HOW_YOU_CAN_HELP.md) links to `pullreview.com`, which [hasn't existed since 2018](https://blog.8thcolor.com/en/2018/02/the-end/). Should the `PullReview or` part just be removed, or is there a different service being used now?

**Comment by deivid-rodriguez** [comment]
It should be removed :+1:.

**Comment by duckinator** [comment]
Closed by https://github.com/rubygems/bundler/pull/7577/commits/7abd3176300d5861e3ee581c6218add3265bbbb5, included in #7577.
