### ISSUE TITLE
Update codeclimate to use correct repository

### ISSUE THREAD

**Issue by duckinator** [rubygems/bundler#7581]
In the process of updating GitHub for #7577, I discovered that CodeClimate is still configured for `bundler/bundler`. If someone sets up `rubygems/bundler` on CodeClimate (I'm not sure if there's a way to tell them a repo has moved, or if you just need to set it up again), I can update the link. :+1:

**Comment by hsbt** [comment]
@duckinator I added rubygems/bundler to codeclimate again.

see https://codeclimate.com/github/rubygems/bundler

Is it ok for your order?

**Comment by duckinator** [comment]
@hsbt yup, that's what I needed! Thank you!
