### ISSUE TITLE
i can't run bundle install 

### ISSUE THREAD

**Issue by Manarhamad** [rubygems/bundler#7604]
i can't run bundle install i have installed the latest ruby on rails on windows 10 x64 pc 
erro screen below 
[Rails error.txt](https://github.com/rubygems/bundler/files/4112340/Rails.error.txt)

**Comment by Manarhamad** [comment]
C:\Sites\test_install>ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
C:\Sites\test_install>rails -v
Could not find gem 'puma (~> 3.7) x86-mingw32' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
C:\Sites\test_install>phantomjs -v
2.1.1
problem is i have a training session needs to be done with ruby in rails 
your reply will be very helpful , Thanks

**Comment by colby-swandale** [comment]
Apologies for the late reply. Please see https://github.com/rubygems/bundler/issues/5501#issuecomment-284525933 which has some information on how to resolve your bundler issue
