### ISSUE TITLE
LoadError: cannot load such file -- <file_name>

### ISSUE THREAD

**Issue by dmitriy-sokolyanskiy** [rubygems/bundler#7606]
Ubuntu 18
Ruby 2.6.3
$gem -v  2.7.6
bundler -v 2.1.4
Installed using "gem install bundler"

When running "bundle install" in a Ruby project:
path from gem which hosting on Github has been added to $LOAD_PATH but then when I open $LOAD_PATH over irb , this path is absent there. And when I try to run app that use this gem it throws an error: LoadError: cannot load such file -- <file_name>
I prepare the examples:
"exam" gem on github - https://github.com/dmitriy-sokolyanskiy/exam
"check" app that use the gem above - https://github.com/dmitriy-sokolyanskiy/check
`my@pc:/check$` **bundle install / update**
`my@pc:/check$` **bundle info exam**
my@pc:/check$ ruby runner.rb

```
Traceback (most recent call last):
2: from runner.rb:1:in '<main>'
1: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in 'require'
/usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in **'require': cannot load such file -- exam (LoadError)**
```

**gem which exam**

`ERROR:  Can't find Ruby library file or shared library exam`

**In irb:**
```
require "exam"
LoadError (cannot load such file -- exam)
2.6.3 :001 > $LOAD_PATH << "/home/geek/.rvm/gems/ruby-2.6.3@check/bundler/gems/exam-90c9b70847c2/lib"
2.6.3 :003 > require "exam"
 => true 
```

**gem env**
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.2
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/pc/.rvm/gems/ruby-2.6.3@check
  - USER INSTALLATION DIRECTORY: /home/pc/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /usr/share/rvm/rubies/ruby-2.6.3/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/pc/.rvm/gems/ruby-2.6.3@check/bin
  - SPEC CACHE DIRECTORY: /home/pc/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/pc/.rvm/gems/ruby-2.6.3@check
     - /home/pc/.rvm/gems/ruby-2.6.3@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/pc/.rvm/gems/ruby-2.6.3@check/bin
     - /home/pc/.rvm/gems/ruby-2.6.3@global/bin
     - /usr/share/rvm/rubies/ruby-2.6.3/bin
     - /usr/share/rvm/bin`

**Comment by deivid-rodriguez** [comment]
Hei @dmitriy-sokolyanskiy!

I think the problem is that by using `ruby runner.rb` you're not telling `ruby` anywhere to use bundler to setup the dependencies. What you're doing manually inside `irb` is what `bundler/setup` does.

So either `bundle exec ruby runner.rb` or `ruby -rbundler/setup runner.rb` should get you back on track.

Let me know if that works for you, and please close the ticket if that's the case :)

**Comment by dmitriy-sokolyanskiy** [comment]
Hello, @deivid-rodriguez 
Great. Thanks a lot. Sorry for the false issue.

**Comment by deivid-rodriguez** [comment]
No problem!
