### ISSUE TITLE
CHANGELOG is out of date on master (does not mention 2.1.4)

### ISSUE THREAD

**Issue by joehorsnell** [rubygems/bundler#7607]
Hi,

Is it intentional that changes on the `2-1-stable` branch, including the [CHANGELOG.md](https://github.com/rubygems/bundler/compare/master..2-1-stable#diff-4ac32a78649ca5bdd8e0ba38b7006a1e) are not on master? It confused me slightly when I saw Bundler [2.1.4](https://rubygems.org/gems/bundler/versions/2.1.4) in RubyGems, but no mention of it in the `CHANGELOG`.

Thanks.

**Comment by deivid-rodriguez** [comment]
No, I forgot to update the master branch. I'll fix it now.
