### ISSUE TITLE
gem install bundler - fails

### ISSUE THREAD

**Issue by Mohithchowdary** [rubygems/bundler#7634]
![Screenshot_20200216-072843](https://user-images.githubusercontent.com/35984716/74598280-e1afd400-5094-11ea-98ba-a4480756d611.jpg)
can you guys help me to fix this problem?
I have installed kali nethunter on my android device. After i did the terminal update.. i am facing these errors. Please help me to resolve this issue.

**Comment by colby-swandale** [comment]
This is not a problem specific to Bundler. It seems that the RubyGems.org SSL Certificate Authority is not in your devices CA trust store. I suggest checking with your operation system to ensure your trust store is up to the date so you can connect to RubyGems.org securely.
