### ISSUE TITLE
Codeanywhere: Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by nzerobe** [rubygems/bundler#7653]
Errno::EDQUOT: Disk quota exceeded @ rb_sysopen - /home/cabox/.rvm/gems/ruby-2.6.3@dev-exam/bundler.lock

Cannot run `bundle install` or `bundle update`

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by colby-swandale** [comment]
Hi it seems like this is an error not related to Bundler, see `Errno::EDQUOT Disk quota exceeded`. I suggest checking your filesystem has enough space available for Bundler.
